declare @ANO int 

set @ANO = 2025 

SELECT CODCOLIGADA,NOME,NUMCONTLOC,CODTB2FLX,DESCEVENTFIN,
[1] 'JANEIRO',
[2]'FEVEREIRO',
[3]'MARÇO',
[4]'ABRIL',
[5]'MAIO',
[6]'JUNHO',
[7]'JULHO',
[8]'AGOSTO',
[9]'SETEMBRO',
[10]'OUTUBRO',
[11]'NOVEMBRO',
[12]'DEZEMBRO',CODCCUSTO ,NOMECCUSTO
         FROM   (
--LANÇAMENTOS IMOBILIARIO
SELECT  FLAN.CODCOLIGADA ,DATEPART (MM,FLANBAIXA.DATABAIXA )MM, FCFO.NOME,
NUMCONTLOC,  
FLAN.CODTB2FLX , 
		CASE	WHEN XALGTIPOEVENTOFINANCEIRO.DESCTIPOEVENTFIN LIKE '%COMPLEMENTAR%' THEN 'COMPLEMENTAR'
		WHEN XALGTIPOEVENTOFINANCEIRO.DESCTIPOEVENTFIN LIKE '%LOCAÇÃO%' THEN 'LOCAÇÃO'
		ELSE XALGTIPOEVENTOFINANCEIRO.DESCTIPOEVENTFIN END DESCEVENTFIN ,
		FLANBAIXA.VALORBAIXA,FLAN.CODCCUSTO,GCCUSTO.NOME 'NOMECCUSTO'     
FROM	FCFO,XALGEVENTOFINANCEIRO,XALGEVENTOFINANCEIRODISTRIBUIC,XALGCONTRATOLOC,
		XALGCONTRATOLOCIMOVEL,XALGIMOVEL,FLAN,XALGPARAM,FLANBAIXA,XALGTIPOEVENTOFINANCEIRO,GCCUSTO  
WHERE 
  XALGEVENTOFINANCEIRO.CODTIPOEVENTFIN = XALGTIPOEVENTOFINANCEIRO.CODTIPOEVENTFIN  AND 
  XALGEVENTOFINANCEIRO.CODCOLEVENTFIN = XALGTIPOEVENTOFINANCEIRO.CODCOLTIPOEVENTFIN  AND 
  XALGEVENTOFINANCEIRO.CODEVENTFIN = XALGEVENTOFINANCEIRODISTRIBUIC.CODEVENTFIN  AND 
  XALGEVENTOFINANCEIRO.CODCOLEVENTFIN = XALGEVENTOFINANCEIRODISTRIBUIC.CODCOLEVENTFIN  AND 
  XALGEVENTOFINANCEIRO.CODEVENTFIN = XALGEVENTOFINANCEIRODISTRIBUIC.CODEVENTFIN  AND 
  XALGEVENTOFINANCEIRO.CODCONTLOC = XALGCONTRATOLOC.CODCONTLOC  AND 
  XALGEVENTOFINANCEIRO.CODCOLEVENTFIN = XALGCONTRATOLOC.CODCOLCONTLOC  AND 
  XALGCONTRATOLOCIMOVEL.CODCONTLOC = XALGCONTRATOLOC.CODCONTLOC  AND 
  XALGCONTRATOLOCIMOVEL.CODCOLIMOVEL = XALGCONTRATOLOC.CODCOLCONTLOC  AND 
  XALGCONTRATOLOCIMOVEL.CODIMOVEL = XALGIMOVEL.CODIMOVEL  AND 
  XALGCONTRATOLOCIMOVEL.CODCOLIMOVEL = XALGIMOVEL.CODCOLIMOVEL  AND 
  XALGEVENTOFINANCEIRODISTRIBUIC.CODCOLEVENTFIN = FLAN.CODCOLIGADA  AND 
  XALGEVENTOFINANCEIRODISTRIBUIC.IDLAN = FLAN.IDLAN  AND 
  DATEPART (YYYY,FLANBAIXA.DATABAIXA ) =@ANO  AND 
  FLAN.CODCOLIGADA =1  AND 
  XALGEVENTOFINANCEIRO.CODCOLEVENTFIN = XALGPARAM.CODCOLIGADA  AND 
  XALGEVENTOFINANCEIRO.CODPARAMFIN = XALGPARAM.IDALGPARAM  AND 
  FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA   AND 
  FCFO.CODCFO = FLAN.CODCFO   AND 
  FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA   AND 
  FLANBAIXA.IDLAN = FLAN.IDLAN  AND 
  GCCUSTO.CODCOLIGADA = FLAN.CODCOLIGADA   AND 
  GCCUSTO.CODCCUSTO = FLAN.CODCCUSTO  AND 
  FLAN.IDLAN <> 1876620  AND 
  FLANBAIXA.CODCXA <>'9999999'  AND
  FLANBAIXA.STATUS =0  
  AND FLAN.IDLAN IN (SELECT INTEGRACHAVE FROM ZT_BAIXAALG_INTEGRACHAVE WHERE CODCOLIGADA =1 )
  
 )  A 
PIVOT (SUM(VALORBAIXA)
FOR MM IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12]))P

ORDER BY 2,1,3

